import React from 'react'
import {
    Navbar,
    NavDropdown,
    Nav,
    Container,
    FormControl,
    Form,
  } from "react-bootstrap";
import Button from "react-bootstrap/Button";
import './Navbar.css'
import { Link } from 'react-router-dom';







function Navbarapp() {
    return (
     
        <div>
             {/**Navbar import */}
      <div className="cont-header">
        <Navbar className="contai" expand="lg">
          <Container className="ul-container">
            <Navbar.Brand
              style={{ color: "white", margin: "0 50px 0 0" }}
              href="#home"
            >
              <div className="cont-color">
                <h1 className="colorido" style={{ color: "yellow" }}>
                  A
                </h1>
                <h1 className="colorido" style={{ color: "green" }}>
                  G
                </h1>
                <h1 className="colorido" style={{ color: "blue" }}>
                  R
                </h1>
                <h1 className="colorido" style={{ color: "white" }}>
                  O
                </h1>
                <h1 className="colorido" style={{ color: "orange" }}>
                  M
                </h1>
                <h1 className="colorido" style={{ color: "violet" }}>
                  P
                </h1>
                <h1 className="colorido" style={{ color: "purple" }}>
                  R
                </h1>
                <h1 className="colorido" style={{ color: "grey" }}>
                  E
                </h1>
                <h1 className="colorido" style={{ color: "aqua" }}>
                  N
                </h1>
                <h1 className="colorido" style={{ color: "red" }}>
                  X
                </h1>
              </div>
            </Navbar.Brand>
            <Navbar.Toggle className="icono" aria-controls="basic-navbar-nav" />
            <Navbar.Collapse id="basic-navbar-nav">
              <Nav className="me-auto">
                <Nav.Link
                  style={{ color: "white", marginRight: "20px" }}
                  href="#home"
                >
                  Inicio
                </Nav.Link>
              
                <NavDropdown title="Quienes Somos" id="basic-nav-dropdown">

                 
                  <NavDropdown.Item href="#mision">Mision</NavDropdown.Item>
                  <NavDropdown.Item href="#vision">Vision</NavDropdown.Item>
                  <NavDropdown.Item href="#historia">Historia</NavDropdown.Item>
                  <NavDropdown.Item href="#action/3.3">
                    Familias
                  </NavDropdown.Item>
                </NavDropdown>

                <NavDropdown title="Productos" id="basic-nav-dropdown">
                  <NavDropdown.Item href="#action/3.1">Frutas</NavDropdown.Item>
                  <NavDropdown.Item href="#action/3.2">
                    Verduras
                  </NavDropdown.Item>
                  <NavDropdown.Item href="#action/3.3">
                    Vegetales
                  </NavDropdown.Item>
                  <NavDropdown.Item href="#action/3.3">
                    Frutos secos
                  </NavDropdown.Item>
                </NavDropdown>

                <Nav.Link
                  style={{ color: "white", marginRight: "20px" }}
                  href="#link"
                >
                  Galeria
                </Nav.Link>
                <Nav.Link
                  style={{ color: "white", marginRight: "50px" }}
                    href="../Registro/Formulario" 
                >
                
               <li> <Link to='/Login'>
                Login
                </Link></li>
                <li> <Link  to='/Formulario/*'>
                Registrarse
                </Link></li>
                </Nav.Link>

              </Nav>

              <Form className="d-flex" style={{height:'35px', width:'auto'}}>
                <FormControl
                  type="search"
                  placeholder="Productos"
                  className="me-2"
                  aria-label="Search"
                />
                <Button style={{color:'white', border:'white 1px solid'}} variant="outline-success">Buscar</Button>
              </Form>
              
            </Navbar.Collapse>
        
          </Container>
        </Navbar>
        <div className="cont-nav">
          <h1 className="center">Agromprenx</h1>
        </div>
        {/* Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections */}
        <div className="ola" style={{ height: "150px", overflow: "hidden" }}>
          <svg
            viewBox="0 0 500 150"
            preserveAspectRatio="none"
            style={{ height: "100%", width: "100%" }}
          >
            <path
              d="M0.00,49.98 C149.99,150.00 349.20,-49.98 500.00,49.98 L500.00,150.00 L0.00,150.00 Z"
              style={{ stroke: "none", fill: "hsla(0, 2%, 50%, 0.33)" }}
            />
             <div>
          
        </div>
        
          </svg>
        </div>
      </div>
      
        </div>
        



    )
}

export default Navbarapp
